In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
hr=pd.read_csv(r"C:\ksr\data science\DS_batch1\datasets\HR_comma_sep.csv")

In [3]:
hr.head(2)

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   

   time_spend_company  Work_accident  left  promotion_last_5years  \
0                   3              0     1                      0   
1                   6              0     1                      0   

  Departments   salary  
0        sales     low  
1        sales  medium

In [4]:
hr.shape

(14999, 10)

In [5]:
hr.columns

Index(['satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident', 'left',
       'promotion_last_5years', 'Departments ', 'salary'],
      dtype='object')

In [6]:
hr1=hr.copy()

In [7]:
hr1.rename(columns=lambda x:x.strip(),inplace=True)

In [8]:
hr1.columns

Index(['satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident', 'left',
       'promotion_last_5years', 'Departments', 'salary'],
      dtype='object')

In [9]:
hr1.dtypes

satisfaction_level       float64
last_evaluation          float64
number_project             int64
average_montly_hours       int64
time_spend_company         int64
Work_accident              int64
left                       int64
promotion_last_5years      int64
Departments               object
salary                    object
dtype: object

# dummy coding 

In [10]:
hr2=pd.get_dummies(hr1,drop_first=True)

In [11]:
hr1.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years Departments  \
0                   3              0     1                      0       sales   
1                   6              0     1                      0       sales   
2                   4              0     1                      0       sales   
3                   5              0     1                      0       sales   
4                   3              0     1                      0       sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [13]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
hr1["salary1"]=lb.fit_transform(hr1["salary"])

In [14]:
import researchpy as rp

In [15]:
rp.summary_cat(hr["salary"])

Variable Outcome  Count  Percent
0   salary     low   7316    48.78
1           medium   6446    42.98
2             high   1237     8.25

In [16]:
rp.summary_cat(hr1["salary1"])

Variable  Outcome  Count  Percent
0  salary1        1   7316    48.78
1                 2   6446    42.98
2                 0   1237     8.25

In [21]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
lb.fit(hr["salary"])
hr1["salary2"]=lb.transform(hr["salary"])

In [22]:
hr1.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years Departments  \
0                   3              0     1                      0       sales   
1                   6              0     1                      0       sales   
2                   4              0     1                      0       sales   
3                   5              0     1                      0       sales   
4                   3              0     1                      0       sales   

   salary  salary1  salary2  
0     low        1        1  
1  medium        2        2  
2  medium        2        2  
3     low        1        1  
4     low        1        1

In [23]:
rp.summary_cat(hr1["salary2"])

Variable  Outcome  Count  Percent
0  salary2        1   7316    48.78
1                 2   6446    42.98
2                 0   1237     8.25

In [24]:
hr1.columns

Index(['satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident', 'left',
       'promotion_last_5years', 'Departments', 'salary', 'salary1', 'salary2'],
      dtype='object')

In [25]:
hr1.drop(["salary1","salary2"],axis=1,inplace=True)

In [26]:
hr1["salary"]=lb.fit_transform(hr1["salary"])
hr1["Departments"]=lb.fit_transform(hr1["Departments"])

# Dividing the data into training and test

In [27]:
from sklearn.model_selection import train_test_split
train,test=train_test_split(hr1,test_size=0.3,random_state=0)
print(train.shape,test.shape)

(10499, 10) (4500, 10)


In [28]:
x_train=train.drop(["left"],axis=1)
y_train=train["left"]
x_test=test.drop(["left"],axis=1)
y_test=test["left"]

In [30]:
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression(solver="liblinear")
lg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [31]:
lg.score(x_train,y_train)

0.7646442518335079

In [33]:
from sklearn.linear_model import LogisticRegressionCV
lg1=LogisticRegressionCV(solver="liblinear")
lg1.fit(x_train,y_train)

LogisticRegressionCV(Cs=10, class_weight=None, cv=None, dual=False,
                     fit_intercept=True, intercept_scaling=1.0, l1_ratios=None,
                     max_iter=100, multi_class='auto', n_jobs=None,
                     penalty='l2', random_state=None, refit=True, scoring=None,
                     solver='liblinear', tol=0.0001, verbose=0)

In [34]:
lg1.score(x_train,y_train)

0.7726450138108392

# model building through dummy coding metholdogy

In [35]:
from sklearn.model_selection import train_test_split
train1,test1=train_test_split(hr2,test_size=0.3,random_state=0)
print(train1.shape,test1.shape)

(10499, 19) (4500, 19)


In [36]:
x_train1=train1.drop(["left"],axis=1)
y_train1=train1["left"]
x_test1=test1.drop(["left"],axis=1)
y_test1=test1["left"]

In [37]:
from sklearn.linear_model import LogisticRegression
lg2=LogisticRegression(solver="liblinear")
lg2.fit(x_train1,y_train1)
lg2.score(x_train1,y_train1)

0.7898847509286598

In [38]:
from sklearn.linear_model import LogisticRegressionCV
lg3=LogisticRegressionCV(solver="liblinear")
lg3.fit(x_train1,y_train1)
lg3.score(x_train1,y_train1)

0.7902657395942471

# Building logistic regression with pycaret

In [39]:
from pycaret.classification import *

In [40]:
exp_clf=setup(data=hr,target="left")

 
Setup Succesfully Completed!


In [41]:
lr=create_model("lr")

Accuracy     AUC  Recall   Prec.      F1   Kappa
0       0.8895  0.9268  0.7960  0.7538  0.7743  0.7013
1       0.8990  0.9410  0.7760  0.7951  0.7854  0.7194
2       0.8867  0.9379  0.7600  0.7631  0.7615  0.6872
3       0.9086  0.9406  0.8040  0.8105  0.8072  0.7473
4       0.8876  0.9279  0.7440  0.7750  0.7592  0.6859
5       0.8876  0.9394  0.8040  0.7444  0.7731  0.6985
6       0.8829  0.9276  0.7360  0.7635  0.7495  0.6731
7       0.8933  0.9389  0.8080  0.7594  0.7829  0.7123
8       0.8914  0.9239  0.7840  0.7656  0.7747  0.7032
9       0.9018  0.9405  0.8080  0.7860  0.7968  0.7321
Mean    0.8928  0.9344  0.7820  0.7716  0.7765  0.7060
SD      0.0076  0.0066  0.0257  0.0191  0.0166  0.0213

In [42]:
from sklearn.linear_model import LogisticRegressionCV
lg3=LogisticRegressionCV(solver="liblinear")
lg3.fit(x_train1,y_train1)
lg3.score(x_train1,y_train1)

0.7902657395942471

In [43]:
lr.solver

'lbfgs'

In [44]:
from sklearn.linear_model import LogisticRegressionCV
lg3=LogisticRegressionCV(solver="lbfgs")
lg3.fit(x_train1,y_train1)
lg3.score(x_train1,y_train1)

0.7915039527574055

In [45]:
lr.C

1.0

In [46]:
lr.class_weight

In [47]:
lr.classes_

array([0, 1], dtype=int64)

In [48]:
lr.coef_

array([[-2.01965972,  1.15752466,  0.00876868,  2.04724143, -2.72665592,
        -1.7633861 , -0.88386035, -0.46747242,  1.90367418, -0.82881703,
        -2.75677883, -0.01220111,  0.35605432,  1.91135258,  1.15457048,
        -0.89539412, -0.81924547, -1.7335725 , -0.62159077, -0.29049078,
        -0.80672741, -0.08868249,  0.29977937, -0.51973213, -0.10580017,
        -0.43400347, -0.05321687,  0.02296863,  0.08544614, -1.82601218,
         0.18443042, -0.24887742]])

In [49]:
hr.shape

(14999, 10)

In [50]:
hr2.shape

(14999, 19)

In [51]:
hr.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  \
0                   3              0     1                      0   
1                   6              0     1                      0   
2                   4              0     1                      0   
3                   5              0     1                      0   
4                   3              0     1                      0   

  Departments   salary  
0        sales     low  
1        sales  medium  
2        sales  medium  
3        sales     low  
4        sales     low

In [52]:
hr.columns

Index(['satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident', 'left',
       'promotion_last_5years', 'Departments ', 'salary'],
      dtype='object')

In [53]:
hr.rename(columns=lambda x:x.strip(),inplace=True)

In [54]:
hr.columns

Index(['satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident', 'left',
       'promotion_last_5years', 'Departments', 'salary'],
      dtype='object')

In [70]:
hr4=hr.copy()

In [71]:
hr4.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years Departments  \
0                   3              0     1                      0       sales   
1                   6              0     1                      0       sales   
2                   4              0     1                      0       sales   
3                   5              0     1                      0       sales   
4                   3              0     1                      0       sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [72]:
hr4["number_project"]=hr4["number_project"].astype("object")

In [73]:
hr4.dtypes

satisfaction_level       float64
last_evaluation          float64
number_project            object
average_montly_hours       int64
time_spend_company         int64
Work_accident              int64
left                       int64
promotion_last_5years      int64
Departments               object
salary                    object
dtype: object

In [74]:
hr4.columns

Index(['satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident', 'left',
       'promotion_last_5years', 'Departments', 'salary'],
      dtype='object')

In [75]:
hr4["time_spend_company"]=hr4["time_spend_company"].astype("object")



In [76]:
hr4.dtypes

satisfaction_level       float64
last_evaluation          float64
number_project            object
average_montly_hours       int64
time_spend_company        object
Work_accident              int64
left                       int64
promotion_last_5years      int64
Departments               object
salary                    object
dtype: object

In [77]:
hr5=pd.get_dummies(hr4)

In [78]:
hr5.shape

(14999, 33)

In [69]:
hr["Work_accident"].value_counts()

0    12830
1     2169
Name: Work_accident, dtype: int64

In [79]:
x_train3=hr5.drop(["left"],axis=1)
y_train3=hr5["left"]


In [80]:
from sklearn.linear_model import LogisticRegressionCV
lg3=LogisticRegressionCV(solver="liblinear")
lg3.fit(x_train3,y_train3)
lg3.score(x_train3,y_train3)

0.8978598573238216

In [82]:
from sklearn.model_selection import train_test_split
train3,test3=train_test_split(hr5,test_size=0.3,random_state=0)
print(train3.shape,test3.shape)

(10499, 33) (4500, 33)


In [85]:
x_train3=train3.drop(["left"],axis=1)
y_train3=train3["left"]
x_test3=test3.drop(["left"],axis=1)
y_test3=test3["left"]

In [86]:
from sklearn.linear_model import LogisticRegressionCV
lg3=LogisticRegressionCV(solver="liblinear")
lg3.fit(x_train3,y_train3)
lg3.score(x_train3,y_train3)

0.8928469378036004

In [87]:
lg3.Cs_

array([1.00000000e-04, 7.74263683e-04, 5.99484250e-03, 4.64158883e-02,
       3.59381366e-01, 2.78255940e+00, 2.15443469e+01, 1.66810054e+02,
       1.29154967e+03, 1.00000000e+04])

In [88]:
lg3.n_iter_

array([[[ 6,  9, 12, 14, 14, 16, 16, 16, 16, 16],
        [ 6,  9, 12, 14, 14, 16, 16, 16, 16, 16],
        [ 6,  9, 12, 14, 14, 16, 16, 16, 16, 16],
        [ 6,  9, 12, 14, 14, 16, 16, 16, 16, 16],
        [ 6,  9, 12, 14, 15, 16, 16, 16, 16, 16]]])

In [89]:
lg3.scores_

{1: array([[0.75904762, 0.75857143, 0.86      , 0.87714286, 0.89238095,
         0.89428571, 0.89428571, 0.89380952, 0.89380952, 0.89380952],
        [0.75857143, 0.75857143, 0.86380952, 0.87619048, 0.88142857,
         0.88714286, 0.88714286, 0.88714286, 0.88714286, 0.88714286],
        [0.75857143, 0.75857143, 0.8647619 , 0.87714286, 0.88428571,
         0.88952381, 0.88952381, 0.88952381, 0.88952381, 0.88952381],
        [0.75857143, 0.75857143, 0.85666667, 0.8752381 , 0.88047619,
         0.88380952, 0.8852381 , 0.88571429, 0.88571429, 0.88571429],
        [0.75893283, 0.75893283, 0.85231062, 0.88804192, 0.89518818,
         0.89757027, 0.89852311, 0.89899952, 0.89852311, 0.89899952]])}