In [1]:
import numpy as np

In [2]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_distributor_init',
 '_global

In [3]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [4]:
np.arange(5,dtype=float)

array([0., 1., 2., 3., 4.])

In [5]:
np.arange(100,110)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [6]:
np.arange(100,120,2)

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118])

In [8]:
abc=np.array([1,4,10,19,20])

In [9]:
abc

array([ 1,  4, 10, 19, 20])

In [10]:
print(abc)

[ 1  4 10 19 20]


In [11]:
abc1=(10,15,20,25)

In [12]:
np.array(abc1)

array([10, 15, 20, 25])

In [13]:
abc2=[10,15,20,25]

In [14]:
np.array(abc2)

array([10, 15, 20, 25])

In [15]:
abc2={10,15,20,25}
np.array(abc2)

array({25, 10, 20, 15}, dtype=object)

In [16]:
abc3=[10,20,40,"india","Hello"]

In [17]:
np.array(abc3)

array(['10', '20', '40', 'india', 'Hello'], dtype='<U11')

In [18]:
salary=np.array([10000,15000,18000,20000,40000])

In [19]:
len(salary)

5

In [20]:
expenses=np.array([5000,7000,8000,9000,20000])

In [21]:
len(expenses)

5

In [22]:
savings=salary-expenses

In [23]:
savings

array([ 5000,  8000, 10000, 11000, 20000])

In [24]:
expenses=np.array([5000,7000,8000,9000,20000,60000])

In [25]:
salary-expenses

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [26]:
abc1=[10,20,40,50,60]

In [27]:
abc1*3

[10, 20, 40, 50, 60, 10, 20, 40, 50, 60, 10, 20, 40, 50, 60]

In [28]:
salary*3

array([ 30000,  45000,  54000,  60000, 120000])

In [29]:
salary

array([10000, 15000, 18000, 20000, 40000])

In [30]:
np.sqrt(salary)

array([100.        , 122.47448714, 134.16407865, 141.42135624,
       200.        ])

In [31]:
np.exp(salary)

C:\Users\Koti\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in exp
  """Entry point for launching an IPython kernel.


array([inf, inf, inf, inf, inf])

In [32]:
np.exp(100000)

C:\Users\Koti\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in exp
  """Entry point for launching an IPython kernel.


inf

In [33]:
np.square(salary)

array([ 100000000,  225000000,  324000000,  400000000, 1600000000],
      dtype=int32)

In [34]:
salary

array([10000, 15000, 18000, 20000, 40000])

In [36]:
salary.ndim

1

In [37]:
salary=np.array([[100,200,300,400]])

In [38]:
salary

array([[100, 200, 300, 400]])

In [39]:
salary.ndim

2

In [40]:
salary=np.array([[[100,200,300,400]]])
salary.ndim

3

In [45]:
salary=np.array([[10,20,30,40,50],[15,25,35,45,55]])

In [46]:
salary.ndim

2

In [47]:
salary

array([[10, 20, 30, 40, 50],
       [15, 25, 35, 45, 55]])

In [48]:
salary=np.array([[[100,200,300,400]]])
salary

array([[[100, 200, 300, 400]]])

In [49]:
salary=np.array([10,20,30,40,50])

In [50]:
salary.ndim

1

In [51]:
salary.shape

(5,)

In [52]:
salary=np.array([[10,20,30,40,50],[60,70,80,90,100]])

In [53]:
salary.ndim

2

In [54]:
salary.shape

(2, 5)

In [55]:
salary


array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [56]:
salary=np.array([[10,20],[30,40]])

In [57]:
print(salary)

[[10 20]
 [30 40]]


In [58]:
expenses=np.array([[1,2],[3,4]])
expenses


array([[1, 2],
       [3, 4]])

In [59]:
print(salary)

[[10 20]
 [30 40]]


In [60]:
print(expenses)

[[1 2]
 [3 4]]


In [61]:
salary+expenses

array([[11, 22],
       [33, 44]])

In [62]:
salary*expenses

array([[ 10,  40],
       [ 90, 160]])

In [63]:
np.dot(salary,expenses)

array([[ 70, 100],
       [150, 220]])

In [65]:
abc=[[10,20,30],[40,50,60]]

In [66]:
np.matrix(abc)

matrix([[10, 20, 30],
        [40, 50, 60]])

In [67]:
salary=[10,50,60,70,80,90]

In [68]:
abc=np.array(salary)

In [69]:
abc

array([10, 50, 60, 70, 80, 90])

In [71]:
abc1=abc.reshape(2,3)

In [72]:
abc1

array([[10, 50, 60],
       [70, 80, 90]])

In [73]:
abc1.shape

(2, 3)

In [74]:
abc1.ndim

2

In [75]:
abc=np.array([10,20,30,40,50,60,70])

In [76]:
len(abc)

7

In [77]:
abc.reshape(2,4)

ValueError: cannot reshape array of size 7 into shape (2,4)

In [78]:
abc.reshape(2,3)

ValueError: cannot reshape array of size 7 into shape (2,3)

In [79]:
abc=np.array([10,20,30,40,50,60])

In [80]:
abc.resize(2,3)

In [81]:
abc

array([[10, 20, 30],
       [40, 50, 60]])

In [82]:
salary=np.array([1000,2000,4000,6000,10000])

In [83]:
salary

array([ 1000,  2000,  4000,  6000, 10000])

In [84]:
np.where(salary>5000,True,False)

array([False, False, False,  True,  True])

In [85]:
np.where(salary>5000,"Yes","No")

array(['No', 'No', 'No', 'Yes', 'Yes'], dtype='<U3')

In [88]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_distributor_init',
 '_global

In [90]:
np.zeros([2,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [91]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])