In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
hr=pd.read_csv(r"C:\ksr\data science\DS_batch1\datasets\HR_comma_sep.csv")

In [3]:
hr.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  \
0                   3              0     1                      0   
1                   6              0     1                      0   
2                   4              0     1                      0   
3                   5              0     1                      0   
4                   3              0     1                      0   

  Departments   salary  
0        sales     low  
1        sales  medium  
2        sales  medium  
3        sales     low  
4        sales     low

In [4]:
hr.columns

Index(['satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident', 'left',
       'promotion_last_5years', 'Departments ', 'salary'],
      dtype='object')

In [5]:
hr=hr.rename(columns=lambda x:x.strip())

In [6]:
hr.columns

Index(['satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident', 'left',
       'promotion_last_5years', 'Departments', 'salary'],
      dtype='object')

In [7]:
hr["number_project"]=hr["number_project"].astype(str)
hr["time_spend_company"]=hr["time_spend_company"].astype(str)

In [8]:
hr1=pd.get_dummies(hr)

In [9]:
from sklearn.model_selection import train_test_split
train,test=train_test_split(hr1,test_size=0.3,random_state=0)
print(train.shape,test.shape)

(10499, 33) (4500, 33)


In [11]:
x_train=train.drop(["left"],axis=1)
y_train=train["left"]
x_test=test.drop(["left"],axis=1)
y_test=test["left"]

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import VotingClassifier
from sklearn import model_selection

In [15]:
kfold=model_selection.KFold(n_splits=10)

In [25]:
estimators=[]
model1=LogisticRegression(solver="liblinear")
estimators.append(("logistic",model1))
model2=DecisionTreeClassifier()
estimators.append(("CART",model2))
model3=GaussianNB()
estimators.append(("GB",model3))

In [26]:
ensemble=VotingClassifier(estimators)

In [27]:
results=model_selection.cross_val_score(ensemble,x_train,y_train,cv=kfold)

In [28]:
print(results.mean())

0.9217080212447228


In [29]:
results

array([0.92761905, 0.90666667, 0.91333333, 0.91428571, 0.93809524,
       0.92285714, 0.91714286, 0.92      , 0.92285714, 0.93422307])

In [32]:
abc=[]
model=LogisticRegression(solver="liblinear")
resul_1=model_selection.cross_val_score(model,x_train,y_train,cv=kfold)

In [34]:
resul_1

array([0.90190476, 0.8847619 , 0.88571429, 0.8847619 , 0.89142857,
       0.88857143, 0.88666667, 0.88190476, 0.89619048, 0.90467112])

In [35]:
abc=[]
model=DecisionTreeClassifier()
resul_2=model_selection.cross_val_score(model,x_train,y_train,cv=kfold)
resul_2

array([0.97904762, 0.9752381 , 0.97904762, 0.97809524, 0.97904762,
       0.97714286, 0.98      , 0.97238095, 0.97047619, 0.97998093])

In [36]:
abc=[]
model=GaussianNB()
resul_3=model_selection.cross_val_score(model,x_train,y_train,cv=kfold)
resul_3

array([0.70380952, 0.69047619, 0.6847619 , 0.69714286, 0.72190476,
       0.69904762, 0.68666667, 0.71904762, 0.71809524, 0.69018112])

In [45]:
resul_lg=pd.Series(resul_1)
resul_dt=pd.Series(resul_2)
resul_nb=pd.Series(resul_3)
resul_ovr=pd.Series(results)

In [46]:
model1=pd.concat([resul_lg,resul_dt,resul_nb,resul_ovr],axis=1)

In [47]:
model1

0         1         2         3
0  0.901905  0.979048  0.703810  0.927619
1  0.884762  0.975238  0.690476  0.906667
2  0.885714  0.979048  0.684762  0.913333
3  0.884762  0.978095  0.697143  0.914286
4  0.891429  0.979048  0.721905  0.938095
5  0.888571  0.977143  0.699048  0.922857
6  0.886667  0.980000  0.686667  0.917143
7  0.881905  0.972381  0.719048  0.920000
8  0.896190  0.970476  0.718095  0.922857
9  0.904671  0.979981  0.690181  0.934223

In [48]:
from pycaret.classification import *

In [49]:
clf=setup(data=hr1,target="left")

 
Setup Succesfully Completed!


In [50]:
bd=blend_models()

Accuracy  AUC  Recall   Prec.      F1   Kappa
0       0.9695  0.0  0.9040  0.9658  0.9339  0.9141
1       0.9686  0.0  0.9200  0.9465  0.9331  0.9125
2       0.9733  0.0  0.9160  0.9703  0.9424  0.9251
3       0.9771  0.0  0.9520  0.9520  0.9520  0.9370
4       0.9705  0.0  0.9120  0.9620  0.9363  0.9171
5       0.9705  0.0  0.9320  0.9433  0.9376  0.9183
6       0.9762  0.0  0.9400  0.9592  0.9495  0.9339
7       0.9762  0.0  0.9200  0.9787  0.9485  0.9330
8       0.9752  0.0  0.9400  0.9553  0.9476  0.9314
9       0.9743  0.0  0.9200  0.9705  0.9446  0.9278
Mean    0.9731  0.0  0.9256  0.9604  0.9425  0.9250
SD      0.0030  0.0  0.0141  0.0107  0.0066  0.0085

In [51]:
bd.classes_

array([0, 1], dtype=int64)

In [52]:
bd.estimators_

[QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                               store_covariance=False, tol=0.0001),
 RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                        criterion='gini', max_depth=None, max_features='auto',
                        max_leaf_nodes=None, max_samples=None,
                        min_impurity_decrease=0.0, min_impurity_split=None,
                        min_samples_leaf=1, min_samples_split=2,
                        min_weight_fraction_leaf=0.0, n_estimators=10,
                        n_jobs=None, oob_score=False, random_state=6859,
                        verbose=0, warm_start=False),
 DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                        max_depth=None, max_features=None, max_leaf_nodes=None,
                        min_impurity_decrease=0.0, min_impurity_split=None,
                        min_samples_leaf=1, min_samples_split=2,
                     